[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.87.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

[[redirects]]
  from = "/"
  to =   "https://www.hardcoremachine.cl"
  status = 301

[[redirects]]
  from = "/home"
  to =   "https://www.hardcoremachine.cl"
  status = 301

[[redirects]]
  from = "/eventos"
  to =   "https://www.hardcoremachine.cl/eventos.html"
  status = 301

[[redirects]]
  from = "/galerias"
  to =   "https://www.hardcoremachine.cl/galerias.html"
  status = 301


[[redirects]]
  from = "/artistas"
  to =   "https://beta.segundao.la/artistas.html"
  status = 301
